# Generated by Django 6.0.8 on 2026-08-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional CSS icon class (e.g. a Font Awesome class).', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Property type',
                'verbose_name_plural': 'Property types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='One or two lines used on cards and listings.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('under_construction', 'Under Construction'), ('completed', 'Completed'), ('sold_out', 'Sold Out')], db_index=True, default='upcoming', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Area / town, e.g. Livadia, Larnaca.', max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Optional Google Maps embed URL.')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.CharField(blank=True, help_text="Free text, e.g. 'Q4 2026', when an exact date is unknown.", max_length=100)),
                ('main_image', models.ImageField(blank=True, upload_to='projects/')),
                ('main_image_alt', models.CharField(blank=True, max_length=200)),
                ('brochure', models.FileField(blank=True, upload_to='projects/brochures/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='projects', to='developments.amenity')),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Overall completion, 0-100.')),
                ('title', models.CharField(blank=True, help_text="Short status line, e.g. 'Exterior structure completed'.", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(help_text='Date of this update.')),
                ('image', models.ImageField(blank=True, upload_to='projects/progress/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='developments.project')),
            ],
            options={
                'verbose_name': 'Construction progress update',
                'verbose_name_plural': 'Construction progress updates',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developments.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unit name or number, e.g. 'Apartment 201'.", max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('under_construction', 'Under Construction')], db_index=True, default='available', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('internal_area', models.DecimalField(blank=True, decimal_places=2, help_text='Square metres.', max_digits=8, null=True)),
                ('covered_area', models.DecimalField(blank=True, decimal_places=2, help_text='Square metres.', max_digits=8, null=True)),
                ('balcony_area', models.DecimalField(blank=True, decimal_places=2, help_text='Balcony / veranda, square metres.', max_digits=8, null=True)),
                ('floor', models.CharField(blank=True, help_text="e.g. 'Ground', '2nd', 'Penthouse level'.", max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_on_request', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, upload_to='properties/')),
                ('main_image_alt', models.CharField(blank=True, max_length=200)),
                ('floor_plan', models.ImageField(blank=True, upload_to='properties/floorplans/')),
                ('brochure', models.FileField(blank=True, upload_to='properties/brochures/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='developments.amenity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='developments.project')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='developments.propertytype')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('completed', 'Completed')], db_index=True, default='new', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='developments.project')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='developments.property')),
            ],
            options={
                'verbose_name': 'Lead / viewing request',
                'verbose_name_plural': 'Leads / viewing requests',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developments.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
