# Generated by Django 6.0.8 on 2026-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_in_featured',
            field=models.BooleanField(db_index=True, default=False, help_text="Show this project in the homepage 'Featured Projects' strip (max 5)."),
        ),
        migrations.AddField(
            model_name='project',
            name='show_in_hero',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this project in the homepage hero slider (max 5).'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text="Show this property in the homepage 'Choose an apartment' slider (max 5)."),
        ),
    ]
