# Generated by Django 6.0.8 on 2026-09-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0002_project_show_in_featured_project_show_in_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
