# Generated by Django 6.0.8 on 2026-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0003_property_parking_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='outdoor_areas',
            field=models.TextField(blank=True, help_text="Other outdoor areas as a comma-separated list, e.g. 'Garden 52 m², Pool area 110 m², Covered veranda 22 m²'. Shown as a list on the property page."),
        ),
    ]
